// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CalendarDay: typeof import('./../components/CalendarDay.vue')['default']
    EntryButton: typeof import('./../components/EntryButton.vue')['default']
    EntryButtonGhost: typeof import('./../components/EntryButtonGhost.vue')['default']
    EntryButtonIcon: typeof import('./../components/EntryButtonIcon.vue')['default']
    EntryHint: typeof import('./../components/EntryHint.vue')['default']
    EntryLabel: typeof import('./../components/EntryLabel.vue')['default']
    EntryRadio: typeof import('./../components/EntryRadio.vue')['default']
    EntrySelect: typeof import('./../components/EntrySelect.vue')['default']
    EntryText: typeof import('./../components/EntryText.vue')['default']
    EntryWrapper: typeof import('./../components/EntryWrapper.vue')['default']
    NotifyBadge: typeof import('./../components/NotifyBadge.vue')['default']
    NotifyStatus: typeof import('./../components/NotifyStatus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarButton: typeof import('./../components/SidebarButton.vue')['default']
    TileBase: typeof import('./../components/TileBase.vue')['default']
    TileImage: typeof import('./../components/TileImage.vue')['default']
  }
}
